USE [master]
GO

/****** Object:  Database [alsahelDb]    Script Date: 2/1/2022 11:43:48 AM ******/
CREATE DATABASE [alsahelDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'alsahelDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\alsahelDb.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'alsahelDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\alsahelDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [alsahelDb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [alsahelDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [alsahelDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [alsahelDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [alsahelDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [alsahelDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [alsahelDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [alsahelDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [alsahelDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [alsahelDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [alsahelDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [alsahelDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [alsahelDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [alsahelDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [alsahelDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [alsahelDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [alsahelDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [alsahelDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [alsahelDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [alsahelDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [alsahelDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [alsahelDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [alsahelDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [alsahelDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [alsahelDb] SET RECOVERY FULL 
GO

ALTER DATABASE [alsahelDb] SET  MULTI_USER 
GO

ALTER DATABASE [alsahelDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [alsahelDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [alsahelDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [alsahelDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [alsahelDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [alsahelDb] SET  READ_WRITE 
GO

